redis:
  # if you're deploying to k3s w/o a say longhorn or openebs
  persistence:
    storageClassName: local-path
    enabled: true

  # used target the deployment to a specific node 
  nodeAffinity:
    selectorMatch:
      key: 'k3s.io/hostname'
      values:
      - 'k3s-worker-0.example.com'


postgresql:
  # if you're deploying to k3s w/o a say longhorn or openebs
  persistence:
    storageClassName: local-path
    enabled: true

  # used target the deployment to a specific node 
  nodeAffinity:
    selectorMatch:
      key: 'k3s.io/hostname'
      values:
      - 'k3s-worker-0.example.com'


gitlab:
  # if you're deploying to k3s w/o a say longhorn or openebs
  persistence:
    data:
      storageClassName: local-path
      enabled: true

  # used target the deployment to a specific node 
  nodeAffinity:
    selectorMatch:
      key: 'k3s.io/hostname'
      values:
      - 'k3s-worker-0.example.com'

  env:
    host: 'gitlab.example.org'

    signupEnabled: 'false'
    
    # far from secure. user `pwgen -Bsv1 64` to generate your own keys
    secrets:
       dbKeyBase: 'C7WRbbVbVX4czWMFfvwXTKKKx3M9wwsLjfbn3f3nJPr7pPqgkMPwW3w49kHWdqPm'
       secretKeyBase: 'C7WRbbVbVX4czWMFfvwXTKKKx3M9wwsLjfbn3f3nJPr7pPqgkMPwW3w49kHWdqPm'
       otpKeyBase: 'C7WRbbVbVX4czWMFfvwXTKKKx3M9wwsLjfbn3f3nJPr7pPqgkMPwW3w49kHWdqPm'
