{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "gitlab.fullname" . }}-redis
  labels:
    app: {{ template "gitlab.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: {{ template "gitlab.name" . }}
    release: {{ .Release.Name }}
    component: redis
{{- end }}