apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitlab.fullname" . }}
  labels:
    app: {{ include "gitlab.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: gitlab
spec:
  type: {{ .Values.gitlab.service.type }}
  ports:
    - name: http
      targetPort: http
      port: {{ .Values.gitlab.service.http.port }}
      protocol: TCP
    - name: ssh
      targetPort: ssh
      port: {{ .Values.gitlab.service.ssh.port }}
      protocol: TCP
  selector:
    app: {{ template "gitlab.name" . }}
    release: {{ .Release.Name }}
    component: gitlab

