apiVersion: v1
kind: Service
metadata:
  name: {{ template "gitlab.fullname" . }}
  labels:
    app: {{ include "gitlab.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: gitlab
spec:
  ports:
    - name: http
      targetPort: http
      port: 80
    - name: ssh
      targetPort: ssh
      port: 22
  selector:
    app: {{ template "gitlab.name" . }}
    release: {{ .Release.Name }}
    component: gitlab
