apiVersion: v1
kind: Service
metadata:
  name: {{ template "gitlab.fullname" . }}
  labels:
    app: {{ include "gitlab.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: http
      targetPort: http
      port: {{ .Values.gitlab.env.port | int }}
    - name: ssh
      targetPort: ssh
    {{- if empty .Values.gitlab.env.ssh.port }}
      port: {{ .Values.gitlab.env.ssh.listenPort | int }}
    {{- else }}
      port: {{ .Values.gitlab.env.ssh.port | int }}
    {{- end }}
  selector:
    app: {{ template "gitlab.name" . }}
    release: {{ .Release.Name }}
    component: gitlab
