name: Package changes so helm can access

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: lint chart
        run: helm lint .
                
      - uses: actions/checkout@v2
        with:
          repository: nemonik/helm-charts
          path: helm-charts
          ref: master
          
      - name: Package chart
        run: |
          PROJECT=$(basename ${GITHUB_WORKSPACE})
          PROJECT="${PROJECT/-helm/}"
          cd helm-charts
          mkdir -p sources/${PROJECT}
          cp -Rf ${GITHUB_WORKSPACE} sources/${PROJECT}
          rsync -av --progress ${GITHUB_WORKSPACE} sources/${PROJECT} --exclude helm-charts --exclude .git --exclude *.tgz --exclude example_values.yaml --exclude gitlab-ingress.yaml --exclude example_install.sh --exclude .github --exclude .gitignore --exclude robot.txt
          cd ..
          helm package sources/.
          helm repo index --url https://nemonik.github.io/helm-charts/ .  

      - name: Commit and push changes to my helm charts repository
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: ${GITHUB_WORKSPACE}/helm-charts
          repository: git@github.com:nemonik/helm-charts.git
