name: Package changes so helm can access

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: lint chart
        run: helm lint .

      - name: Package chart
        run: |
          PROJECT=$(basename ${GITHUB_WORKSPACE})
          cd /tmp
          cp -R ${GITHUB_WORKSPACE} ${PROJECT}
          cd ${PROJECT}
          rm -Rf .git
          rm *.tgz
          rm -Rf example_values.yaml gitlab-ingress.yaml example_install.sh .github .gitignore robot.txt
          helm package .
          cp *.tgz ${GITHUB_WORKSPACE}/.
          cd ${GITHUB_WORKSPACE}
          
      - name: Commit and push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: packaged for helm via action 
