name: Package changes so helm can access

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: lint chart
        run: helm lint .
                
      - uses: actions/checkout@v2
        with:
          repository: https://github.com/nemonik/helm-charts.git
          path: ${GITHUB_WORKSPACE}/../helm-charts
          ref: master
          
      - name: Package chart
        run: |
          PROJECT=$(basename ${GITHUB_WORKSPACE})
          PROJECT="${PROJECT/-helm/}"
          cd ../helm-charts
          mkdir -Rf sources/${PROJECT}
          cp -Rf ${GITHUB_WORKSPACE} sources/${PROJECT}
          cd ${PROJECT}
          rm -Rf .git *.tgz example_values.yaml gitlab-ingress.yaml example_install.sh .github .gitignore robot.txt
          cd ..
          helm package sources/.
          helm repo index --url https://nemonik.github.io/helm-charts/ .  

      - name: Commit and push changes to my helm chartsr epository
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: ${GITHUB_WORKSPACE}/../helm-charts
          repository: git@github.com:nemonik/helm-charts.git
